"""description of changes

Revision ID: 5fee67f7bd9f
Revises: 64de6342ee3f
Create Date: 2026-03-18 22:17:43.626656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fee67f7bd9f'
down_revision: Union[str, Sequence[str], None] = '64de6342ee3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('task_completed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['u_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('house_number', sa.String(length=50), nullable=False),
    sa.Column('landmark', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=170), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taskerskill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasker_id', sa.Integer(), nullable=False),
    sa.Column('tasker_skill', sa.Enum('PAINTING', 'CONSTRUCTION', 'CARPENTER', name='skills_enum'), nullable=False),
    sa.ForeignKeyConstraint(['tasker_id'], ['tasker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tasker_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('task_title', sa.String(length=100), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('task_tag', sa.Enum('PAINTING', 'CONSTRUCTION', 'CARPENTER', name='Task_tags_enum'), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'INR', name='currency_enum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', name='payment_method_enum'), nullable=False),
    sa.Column('task_status', sa.Enum('POSTED', 'ASSIGNED', 'COMPLETED', 'CANCELED', 'INPROGRESS', name='Task_status_enum'), nullable=False),
    sa.Column('task_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tasker_id'], ['tasker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('taskerskill')
    op.drop_table('address')
    op.drop_table('tasker')
    op.drop_table('customer')
    # ### end Alembic commands ###
