"""update expire_at column

Revision ID: 64de6342ee3f
Revises: 678fe2da733a
Create Date: 2026-03-06 12:20:35.133479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64de6342ee3f'
down_revision: Union[str, Sequence[str], None] = '678fe2da733a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('permissions', 'content',
    #            existing_type=postgresql.ENUM('DASHBOARD', 'USERS', 'TASKS', name='user_permission_enum'),
    #            type_=sa.Enum('DASHBOARD', 'USERS', 'TASKS', name='user_permission'),
    #            existing_nullable=False)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # op.alter_column('permissions', 'content',
    #            existing_type=sa.Enum('DASHBOARD', 'USERS', 'TASKS', name='user_permission'),
    #            type_=postgresql.ENUM('DASHBOARD', 'USERS', 'TASKS', name='user_permission_enum'),
    #            existing_nullable=False)
    # ### end Alembic commands ###
