"""create refresh token table

Revision ID: 678fe2da733a
Revises: 8094c47bf046
Create Date: 2026-03-02 22:33:00.167122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '678fe2da733a'
down_revision: Union[str, Sequence[str], None] = '8094c47bf046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'content',
               existing_type=sa.Enum('DASHBOARD', 'USERS', 'TASKS', name='user_permission'),
               type_=postgresql.ENUM('DASHBOARD', 'USERS', 'TASKS', name='user_permission_enum'),
               existing_nullable=False)
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
